### ISSUE TITLE
Code is crashing

### ISSUE THREAD

**Issue by iamanas1111** [rajarshisur/Programming-in-Java-NPTEL#1]
![image](https://user-images.githubusercontent.com/85670355/187060467-d117205d-f550-4346-bc17-fcf6e0b5d431.png)

for input 10 and 0 output is 10, but for inputs 0 and 10 exception is thrown.

**Comment by rajarshisur** [comment]
/*This program is to find the GCD (greatest common divisor) of two integers writing a recursive function findGCD(n1,n2). Your function should return -1, if the argument(s) is(are) other than positive number(s).
*/

import java.util.Scanner;

interface GCD {
    public int findGCD(int n1,int n2);
}
//Create a class B, which implements the interface GCD.
class B implements GCD {
    int number_1,number_2;
        
    
    public int findGCD(int number_1, int number_2){
		if(number_1==0 && number_2==0) {
			return -1;
		}
		else if(number_2 == 0){
			return number_1;  
		}
		
		else {
			return findGCD(number_2, number_1%number_2);
		}
        }
 }

public class Question5_2{ 
        public static void main (String[] args){ 
	      B a = new B();   //Create an object of class B
            // Read two numbers from the keyboard
            Scanner sc = new Scanner(System.in);  
             int p1 = sc.nextInt();
             int p2 = sc.nextInt();
            System.out.print(a.findGCD(p1,p2)); 
    } 
}
